### ISSUE TITLE
bug: Reddit error while patc

### ISSUE THREAD

**Issue by weiliang011** [anddea/revanced-patches#298]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Reddit 2024.15.0

### Bug description

Idk, just a bug wjile patching reddit, included all patches except change package name

### Error logs

```shell
- Device Info
ReVanced Manager: 1.18.3
Model: LM-Q630
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.15.0 (Suggested: Any)
Patches version: v2.223.0
Patches added: Custom branding name Reddit
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 10 patches
Open links directly failed: app.revanced.patcher.patch.PatchException: Failed to resolve ScreenNavigatorFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksDirectlyPatch.execute(OpenLinksDirectlyPatch.kt:37)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksDirectlyPatch.execute(OpenLinksDirectlyPatch.kt:13)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:345)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$37(MainActivity.kt:344)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$v-ELoclvC6W1vrKGstBtHifiD5Q(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:923)
Open links externally failed: app.revanced.patcher.patch.PatchException: Failed to resolve ScreenNavigatorFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksExternallyPatch.execute(OpenLinksExternallyPatch.kt:43)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksExternallyPatch.execute(OpenLinksExternallyPatch.kt:16)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:345)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$37(MainActivity.kt:344)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$v-ELoclvC6W1vrKGstBtHifiD5Q(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:923)
Compiling patched dex files
```

### Device Environment

Android 11

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by JakobHunterek** [comment]
I have this issue as well

**Comment by anddea** [comment]
Fixed in the latest dev release.
