### ISSUE TITLE
Visual preferences icons Conflicting with Coustom Branding YouTube Icon

### ISSUE THREAD

**Issue by gigachaand** [anddea/revanced-patches#326]
### Type

Error while patching

### Tools used

Revancify

### Application

19.11.38

### Bug description

Visual preferences icons patch not working when enabling Coustom Branding Icon YouTube patch

![Screenshot_2024-04-17-10-28-48-807_com termux-edit](https://github.com/anddea/revanced-patches/assets/96541364/bdba761f-fd0a-46f8-986d-b3806254f0bf)

### Error logs

```shell
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Hide fullscreen panels excluded 
INFO: Force fullscreen excluded 
INFO: Change player flyout panel toggles excluded 
INFO: Spoof player parameters excluded 
INFO: Hide category bar excluded 
INFO: Enable song search excluded 
INFO: Hide handle excluded 
INFO: Enable gradient loading screen excluded 
INFO: Enable tablet mini player excluded 
INFO: Hide load more button excluded 
INFO: Hide channel avatar section excluded 
INFO: Hide time stamp excluded 
INFO: Hide seekbar excluded 
INFO: Layout switch excluded 
INFO: Translations excluded 
INFO: Disable update screen excluded 
INFO: Spoof device dimensions excluded 
INFO: Disable QUIC protocol excluded 
INFO: Enable debug logging excluded 
INFO: Force video codec excluded 
INFO: Force opus codec excluded 
INFO: Spoof app version excluded 
INFO: Hide collapse button excluded 
INFO: Hide fullscreen button excluded 
INFO: Hide player chapters excluded 
INFO: Hide tooltip content excluded 
INFO: Add splash animation excluded 
INFO: Disable HDR video excluded 
INFO: Custom playback speed excluded 
INFO: Default playback speed excluded 
INFO: Enable tablet navigation bar excluded 
INFO: Alternative thumbnails excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Ambient mode switch succeeded 
INFO: Append time stamps information succeeded 
INFO: Change start page succeeded 
INFO: Custom branding icon YouTube succeeded 
INFO: Custom branding name YouTube succeeded 
INFO: Custom branding wordmark header succeeded 
INFO: Custom double tap length succeeded 
INFO: Custom package name succeeded 
INFO: Custom player overlay opacity succeeded 
INFO: Custom seekbar color succeeded 
INFO: Default video quality succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable haptic feedback succeeded 
INFO: Disable landscape mode succeeded 
INFO: Disable pip notification succeeded 
INFO: Disable rolling number animations succeeded 
INFO: Disable shorts on startup succeeded 
INFO: Disable speed overlay succeeded 
INFO: Enable bottom player gestures succeeded 
INFO: Enable compact controls overlay succeeded 
INFO: Enable external browser succeeded 
INFO: Enable language switch succeeded 
INFO: Enable minimized playback succeeded 
INFO: Enable new splash animation succeeded 
INFO: Enable new thumbnail preview succeeded 
INFO: Enable old quality layout succeeded 
INFO: Enable open links directly succeeded 
INFO: Enable seekbar tapping succeeded 
INFO: Enable wide search bar succeeded 
INFO: Force hide player buttons background succeeded 
INFO: Header switch succeeded 
INFO: Hide account menu succeeded 
INFO: Hide animated button background succeeded 
INFO: Hide auto player popup panels succeeded 
INFO: Hide autoplay button succeeded 
INFO: Hide autoplay preview succeeded 
INFO: Hide button container succeeded 
INFO: Hide captions button succeeded 
INFO: Hide cast button succeeded 
INFO: Hide channel profile components succeeded 
INFO: Hide channel watermark succeeded 
INFO: Hide comment component succeeded 
INFO: Hide crowdfunding box succeeded 
INFO: Hide description components succeeded 
INFO: Hide double tap overlay filter succeeded 
INFO: Hide double tap to like animations succeeded 
INFO: Hide end screen cards succeeded 
INFO: Hide end screen overlay succeeded 
INFO: Hide feed flyout panel succeeded 
INFO: Hide filmstrip overlay succeeded 
INFO: Hide floating microphone succeeded 
INFO: Hide general ads succeeded 
INFO: Hide info cards succeeded 
INFO: Hide latest videos button succeeded 
INFO: Hide layout components succeeded 
INFO: Hide mix playlists succeeded 
INFO: Hide music button succeeded 
INFO: Hide navigation buttons succeeded 
INFO: Hide navigation label succeeded 
INFO: Hide player buttons background succeeded 
INFO: Hide player flyout panel succeeded 
INFO: Hide previous next button succeeded 
INFO: Hide search term thumbnail succeeded 
INFO: Hide seek message succeeded 
INFO: Hide shorts components succeeded 
INFO: Hide snack bar succeeded 
INFO: Hide suggested actions succeeded 
INFO: Hide suggested video overlay succeeded 
INFO: Hide suggestions shelf succeeded 
INFO: Hide toolbar button succeeded 
INFO: Hide trending searches succeeded 
INFO: Hide video ads succeeded 
INFO: Hide voice search button succeeded 
INFO: Keep landscape mode succeeded 
INFO: MaterialYou succeeded 
INFO: MicroG support succeeded 
INFO: Overlay buttons succeeded 
INFO: Quick actions components succeeded 
INFO: Remove viewer discretion dialog succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Sanitize sharing links succeeded 
INFO: Shorts overlay buttons succeeded 
INFO: SponsorBlock succeeded 
WARNING: Disable auto HDR brightness is not supported in this version. Use YouTube 19.08.36 or earlier (Failed to resolve HDRBrightnessFingerprint)
INFO: Swipe controls succeeded 
INFO: Theme succeeded 
INFO: Tuck away preferences succeeded 
SEVERE: Visual preferences icons failed:
app.revanced.patcher.patch.PatchException
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.lang.NullPointerException
	at app.revanced.util.ResourceUtilsKt.copyResources(ResourceUtils.kt:63)
	at app.revanced.patches.youtube.utils.settings.VisualSettingsIconsPatch.execute(VisualSettingsIconsPatch.kt:234)
	at app.revanced.patches.youtube.utils.settings.VisualSettingsIconsPatch.execute(VisualSettingsIconsPatch.kt:15)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	... 24 more
 
INFO: Settings succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiling modified resources 
INFO: Aligning base.apk 
INFO: Signing base.apk 
INFO: Saved to /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.11.38/base-RVX-anddea.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 



Rooted: false
Arch: arm64-v8a
App: YouTube v19.11.38
CLI: inotia00-cli-v4.4.1.jar
Patches: anddea-patches-v2.224.0-dev.6.jar
Integrations: anddea-integrations-v0.151.0-dev.6.apk
Patches argument: -i Ambient mode switch -i Append time stamps information -i Change start page -i Custom branding icon YouTube -i Custom branding name YouTube -i Custom branding wordmark header -i Custom double tap length -i Custom package name -i Custom player overlay opacity -i Custom seekbar color -i Default video quality -i Disable auto captions -i Disable haptic feedback -i Disable landscape mode -i Disable pip notification -i Disable rolling number animations -i Disable shorts on startup -i Disable speed overlay -i Enable bottom player gestures -i Enable compact controls overlay -i Enable external browser -i Enable language switch -i Enable minimized playback -i Enable new splash animation -i Enable new thumbnail preview -i Enable old quality layout -i Enable open links directly -i Enable seekbar tapping -i Enable wide search bar -i Force hide player buttons background -i Header switch -i Hide account menu -i Hide animated button background -i Hide auto player popup panels -i Hide autoplay button -i Hide autoplay preview -i Hide button container -i Hide captions button -i Hide cast button -i Hide channel profile components -i Hide channel watermark -i Hide comment component -i Hide crowdfunding box -i Hide description components -i Hide double tap overlay filter -i Hide double tap to like animations -i Hide end screen cards -i Hide end screen overlay -i Hide feed flyout panel -i Hide filmstrip overlay -i Hide floating microphone -i Hide general ads -i Hide info cards -i Hide latest videos button -i Hide layout components -i Hide mix playlists -i Hide music button -i Hide navigation buttons -i Hide navigation label -i Hide player buttons background -i Hide player flyout panel -i Hide previous next button -i Hide search term thumbnail -i Hide seek message -i Hide shorts components -i Hide snack bar -i Hide suggested actions -i Hide suggested video overlay -i Hide suggestions shelf -i Hide toolbar button -i Hide trending searches -i Hide video ads -i Hide voice search button -i Keep landscape mode -i MaterialYou -i MicroG support -i Overlay buttons -i Quick actions components -i Remove viewer discretion dialog -i Return YouTube Dislike -i Sanitize sharing links -i Settings -i Shorts overlay buttons -i SponsorBlock -i Swipe controls -i Theme -i Tuck away preferences -i Visual preferences icons
```

### Solution

Exclude Coustom Branding Icon YouTube patch

### Additional context

none

### Device Environment

Android 14
HyperOS

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Fixed.
