### ISSUE TITLE
bug: Reddit, 1 patch not compatible with latest version

### ISSUE THREAD

**Issue by 54m4d** [anddea/revanced-patches#327]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Reddit 2024.16.0

### Bug description

`Hide toolbar button` probably not compatible with 2024.16.0, no issues with 2024.15.0

### Error logs

```shell
- Patch Info
App: com.reddit.frontpage v2024.16.0 (Suggested: Any)
Patches version: v2.224.0-dev.6
Patches added: Default
Patches removed: Hide ads, Hide navigation buttons, Premium icon, Hide recently visited shelf, Disable screenshot popup, Remove subreddit dialog, Open links directly, Open links externally, Sanitize sharing links, Settings
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Hide toolbar button failed: app.revanced.patcher.patch.PatchException: Failed to resolve HomePagerScreenFingerprint
 at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
 at app.revanced.patches.reddit.layout.toolbar.ToolBarButtonPatch.execute(ToolBarButtonPatch.kt:50)
 at app.revanced.patches.reddit.layout.toolbar.ToolBarButtonPatch.execute(ToolBarButtonPatch.kt:18)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
 at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
 at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
 at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
 at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
 at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:345)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
 at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$37(MainActivity.kt:344)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$v-ELoclvC6W1vrKGstBtHifiD5Q(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:26)
 at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
Signing APK
Patched APK
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Does this option relevant? Because I cannot see r/place or Reddit recap in toolbar.

**Comment by 54m4d** [comment]
> Is this option relevant? Because I cannot see r/place or Reddit recap in toolbar.

I excluded this patch now, and it seems indeed that it is not relevant anymore, if it continues like this, this patch may be removed in the future. Thanks.
