### ISSUE TITLE
bug: missing strings? 

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#328]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube 19.11.43

### Bug description

Missing something on the patches.

### Error logs

```shell
WARNING: /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/res/values/strings.xml:3359: error: unescaped apostrophe in string 
WARNING: "Live chat header is hidden.\n\nBack button in header won't be hidden.". 
WARNING: /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/res/values/strings.xml:3359: error: not a valid string. 
WARNING: /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/res/values/strings.xml:3360: error: unescaped apostrophe in string 
WARNING: "Live chat header is shown.\n\nBack button in header won't be hidden.". 
WARNING: /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/res/values/strings.xml:3360: error: not a valid string. 
WARNING: /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/res/values/strings.xml: error: file failed to compile. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_110351654374710088336457760945769538287.tmp, compile, --dir, /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/res, --legacy, -o, /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
	at app.revanced.patcher.Patcher.get(Patcher.kt:268)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:323)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_110351654374710088336457760945769538287.tmp, compile, --dir, /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/res, --legacy, -o, /home/runner/work/revanced-extended/revanced-extended/temp/youtube-revanced-extended-19.11.43-arm64-v8a-apk-temporary-files/patcher/apk/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
	... 13 more
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Should be fixed now.
