### ISSUE TITLE
Add support for Reddit 2024.18.0

### ISSUE THREAD

**Issue by Xisrr1** [anddea/revanced-patches#401]
Patching fails.

**Comment by Morafoka69** [comment]
> Patching fails.

I didn't even know there's a new version; I've been trying to patch the version 2024.17.0 and the "Hide toolbar patch" isn't working.
Please help, anddea. I'm using RVX Manager so the Dev releases are showing, and it still didn't work.

Thank you in anticipation. More grease to thy elbows.

**Comment by anddea** [comment]
> I've been trying to patch the version 2024.17.0 and the "Hide toolbar patch" isn't working.

There are no toolbar buttons anymore, at least for me and for some people who reported it. If you patched it, then you could see the error message that the patch is no longer relevant for latest versions. If one patch fails, it doesn't mean that the whole patching process is failed.

**Comment by donw7eed** [comment]
> > I've been trying to patch the version 2024.17.0 and the "Hide toolbar patch" isn't working.
> 
> There are no toolbar buttons anymore, at least for me and for some people who reported it. If you patched it, then you could see the error message that the patch is no longer relevant for latest versions. If one patch fails, it doesn't mean that the whole patching process is failed. 

For me it's failed to patch also 
This is the patch-log

INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Custom branding name Reddit excluded 
INFO: Change package name excluded 
INFO: Hide toolbar button excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Disable screenshot popup succeeded 
INFO: Hide ads succeeded 
INFO: Hide navigation buttons succeeded 
INFO: Hide recently visited shelf succeeded 
INFO: Open links directly succeeded 
INFO: Open links externally succeeded 
INFO: Premium icon succeeded 
INFO: Remove subreddit dialog succeeded 
INFO: Sanitize sharing links succeeded 
INFO: Settings succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiled classes9.dex 
INFO: Compiled classes10.dex 
INFO: Compiled classes11.dex 
INFO: Compiled classes12.dex 
INFO: Compiling modified resources 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:2661: error: expected enum but got (raw string) 0. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:3268: error: expected enum but got (raw string) 1. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:3271: error: expected enum but got (raw string) 1. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:3303: error: expected enum but got (raw string) 1. 
WARNING: error: failed linking references. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL2249802270257696285.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:313)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL2249802270257696285.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 13 more



Rooted: false
Arch: arm64-v8a
App: Reddit v2024.18.0
CLI: inotia00-cli-v4.4.1.jar
Patches: anddea-patches-v2.225.0-dev.1.jar
Integrations: anddea-integrations-v0.152.0-dev.1.apk
Patches argument: -i Disable screenshot popup -i Hide ads -i Hide navigation buttons -i Hide recently visited shelf -i Open links directly -i Open links externally -i Premium icon -i Remove subreddit dialog -i Sanitize sharing links -i Settings

**Comment by n4zk4** [comment]
Patching Reddit 2024.18.0 (with patches v2.225.0-dev.2) fails for me top. Never happened before. Here's the log:

- Device Info
ReVanced Manager: 1.18.1
Model: SM-S916B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.18.0 (Suggested: Any)
Patches version: v2.225.0-dev.2
Patches added: Default
Patches removed: Hide toolbar button
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: false
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 10 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~CYMoM9Y61UMHSUtzX6gvSg==/app.rvx.manager.flutter-xtZM6ISG20ETbrMfL8NlfA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL4484027058307580606.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$37(MainActivity.kt:375)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$v-ELoclvC6W1vrKGstBtHifiD5Q(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~CYMoM9Y61UMHSUtzX6gvSg==/app.rvx.manager.flutter-xtZM6ISG20ETbrMfL8NlfA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL4484027058307580606.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more

**Comment by selfmusing** [comment]
https://github.com/ReVanced/revanced-patches/issues/3099#issuecomment-2088009109

@anddea

**Comment by Xisrr1** [comment]
> 2024.18.1 is out now already xD

It is not going to be fixed soon, it seems. 
https://github.com/ReVanced/revanced-patches/issues/3099

**Comment by Xisrr1** [comment]
Eh so a year later.. 

Can you add support for 2025.17.0 and up?
