### ISSUE TITLE
Reddit 2024.18.1 - patching fails

### ISSUE THREAD

**Issue by Xisrr1** [anddea/revanced-patches#412]
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/res/values/styles.xml:2661: error: expected enum but got (raw string) 0. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/res/values/styles.xml:3268: error: expected enum but got (raw string) 1. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/res/values/styles.xml:3271: error: expected enum but got (raw string) 1. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/res/values/styles.xml:3303: error: expected enum but got (raw string) 1. 
WARNING: error: failed linking references. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1585304, --version-name, 2024.18.1, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL4741670441419016922.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:313)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1585304, --version-name, 2024.18.1, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL4741670441419016922.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.1/base-RVX-anddea-resource-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 13 more

**Comment by Xisrr1** [comment]
@anddea

**Comment by anddea** [comment]
Nothing is changed from https://github.com/anddea/revanced-patches/issues/401, no need to report again.
