### ISSUE TITLE
bug: Append time stamps information patch failing

### ISSUE THREAD

**Issue by 54m4d** [anddea/revanced-patches#438]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YT

### Bug description

Error while patching

### Error logs

```shell
- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 50 patches
Append time stamps information failed: app.revanced.patcher.patch.PatchException: 'Append time stamps information' depends on 'OverrideQualityHookPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve VideoQualityPatchFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
	at app.revanced.patches.youtube.utils.overridequality.OverrideQualityHookPatch.execute(OverrideQualityHookPatch.kt:63)
	at app.revanced.patches.youtube.utils.overridequality.OverrideQualityHookPatch.execute(OverrideQualityHookPatch.kt:23)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hsuHvwTCdC5Nf5dk5fKUQSHxuuY(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:148)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hsuHvwTCdC5Nf5dk5fKUQSHxuuY(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Ripping selected native libs
Aligning APK
Signing APK
Patched APK
```

### Additional context

v2.225.0-dev.9

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Seems like an old error. Clear your manager and try again. What was the last patches version you used?

**Comment by 54m4d** [comment]
@anddea Sorry about this, well, the first thing I tried was to force stop the manager and clear its cache, but that did not help, however, when I tried to do that again now (After some hours), it worked, and I got no errors, I guess this chaos is caused by the GH rate limit, I can't think of something else.
