### ISSUE TITLE
Error while patching

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#542]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 19.20.34

### Bug description

I got an error while i try patch YouTube 19.20.34
via RVX Manager 

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.3
Model: M2012K11AG
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.20.34 (Suggested: 19.20.34)
Patches version: v2.225.0-dev.24
Patches added: Custom branding icon YouTube [App icon: mmt], Custom branding name YouTube [App name: ReVanced Extended], Force custom branding wordmark header, Force hide player buttons background, Hide animated button background, Hide double tap to like animations, Hide shorts dimming, MaterialYou
Patches removed: Custom package name, GmsCore support
Default patch options changed: Toolbar components [Force hide voice search button: true], Overlay buttons [Icon type: rounded], Shorts overlay buttons [Icon type of Shorts: tiktok], Visual preferences icons [Extended icon: extension]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: false
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~-LhFCUeY6c6XeTuMn3fVwg==/app.rvx.manager.flutter-j_55b8E5-hwqYFqQfaMqiw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-BXUETV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-BXUETV/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:487)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hsuHvwTCdC5Nf5dk5fKUQSHxuuY(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~-LhFCUeY6c6XeTuMn3fVwg==/app.rvx.manager.flutter-j_55b8E5-hwqYFqQfaMqiw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-BXUETV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-BXUETV/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
```

### Additional context

RVX Manager 1.20.3
Revanced Patches 2.225.0-dev.24

### Device Environment

Android 14 HyperOS 1.0 Elite HyperOS Lite 24.5.13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KW1J** [comment]
same issue on revancify

**Comment by yurirosas** [comment]
Same on revancify

**Comment by bozander** [comment]
@anddea Fix this problem please
