### ISSUE TITLE
bug: Patching error when "Replace cast button" is chosen. 

### ISSUE THREAD

**Issue by innit86** [anddea/revanced-patches#563]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube Music 7.03.51

### Bug description

Patching error when "Replace cast button" is chosen.
[patch_log.txt](https://github.com/user-attachments/files/15516862/patch_log.txt)

### Error logs

```shell
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Translations excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Amoled succeeded 
INFO: Bitrate default value succeeded 
INFO: Certificate spoof succeeded 
INFO: Change start page succeeded 
INFO: Custom branding icon YouTube Music succeeded 
INFO: Custom branding name YouTube Music succeeded 
INFO: Custom package name succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable dislike redirection succeeded 
INFO: Enable OPUS codec succeeded 
INFO: Enable debug logging succeeded 
INFO: Enable landscape mode succeeded 
INFO: Enable minimized playback succeeded 
INFO: Flyout menu components succeeded 
INFO: GmsCore support succeeded 
INFO: Hide account components succeeded 
INFO: Hide action bar components succeeded 
INFO: Hide ads succeeded 
INFO: Hide double tap overlay filter succeeded 
INFO: Hide layout components succeeded 
INFO: Hide overlay filter succeeded 
INFO: Hide player overlay filter succeeded 
INFO: Navigation bar components succeeded 
INFO: Player components succeeded 
INFO: Remove viewer discretion dialog succeeded 
SEVERE: Replace Cast button failed:
app.revanced.patcher.patch.PatchException: 'Replace Cast button' depends on 'PlayerResponsePatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve PlaybackStartDescriptorFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:43)
	at app.revanced.util.BytecodeUtilsKt.resultOrThrow(BytecodeUtils.kt:35)
	at app.revanced.patches.music.utils.playerresponse.PlayerResponsePatch.execute(PlayerResponsePatch.kt:40)
	at app.revanced.patches.music.utils.playerresponse.PlayerResponsePatch.execute(PlayerResponsePatch.kt:10)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:155)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
	at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:315)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:160)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
	at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:315)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
 
INFO: Restore old style library shelf succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Sanitize sharing links succeeded 
INFO: SponsorBlock succeeded 
INFO: Spoof app version succeeded 
INFO: Video playback succeeded 
INFO: Settings succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiling modified resources 
INFO: Ripping selected native libs 
INFO: Aligning APK 
INFO: Signing APK 
INFO: Saved to /data/data/com.termux/files/home/revancify-data/apps/YouTube-Music-7.03.51/base-RVX-anddea.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 



Rooted: false
Arch: arm64-v8a
App: YouTube-Music v7.03.51
CLI: inotia00-cli-v4.6.1.jar
Patches: anddea-patches-v2.226.0-dev.2.jar
Integrations: anddea-integrations-v0.153.0-dev.1.apk
Patches argument: -i Amoled -i Bitrate default value -i Certificate spoof -i Change start page -i Custom branding icon YouTube Music -i Custom branding name YouTube Music -i Custom package name -i Disable auto captions -i Disable dislike redirection -i Enable OPUS codec -i Enable debug logging -i Enable landscape mode -i Enable minimized playback -i Flyout menu components -i GmsCore support -i Hide account components -i Hide action bar components -i Hide ads -i Hide double tap overlay filter -i Hide layout components -i Hide overlay filter -i Hide player overlay filter -i Navigation bar components -i Player components -i Remove viewer discretion dialog -i Replace Cast button -i Restore old style library shelf -i Return YouTube Dislike -i Sanitize sharing links -i Settings -i SponsorBlock -i Spoof app version -i Video playback
```

### Device Environment

Pixel 7 Pro
Android 14 (May security update)
Magisk Canary 27.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Is it the same for inotia patches? If it is open bug report in his repo.

**Comment by innit86** [comment]
> Is it the same for inotia patches? If it is open bug report in his repo. 

Yes, it also fails when using inotia patches.

**Comment by anddea** [comment]
Open bug report there, he'll fix it, when he has time.

**Comment by innit86** [comment]
> Open bug report there, he'll fix it, when he has time. 

There's no issue tracker on his github.

**Comment by zerozero0022** [comment]
> > Open bug report there, he'll fix it, when he has time.
> 
> There's no issue tracker on his github.

The feature will be removed in the next version of RVX.
