### ISSUE TITLE
bug: failing patch

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#643]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Yt 19.23.40

### Bug description

When i try to patch this happens

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.3
Model: SM-A336E
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.23.40 (Suggested: 19.23.40)
Patches version: v2.226.0-dev.17
Patches added: Custom branding icon YouTube [App icon: mmt_blue], Custom branding name YouTube [App name: RVX Youtube], Force custom branding wordmark header, Force hide player buttons background, Hide Shorts dimming, Hide animated button background, MaterialYou
Patches removed: None
Default patch options changed: Toolbar components [Force hide voice search button: true], Theme [Dark theme background color: #000000 ], Overlay buttons [Icon type: thin], Shorts overlay buttons [Icon type of Shorts: tiktok], Settings for YouTube [RVX settings menu name: RVX Settings], Visual preferences icons [Extended icon: gear]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Remove unused library: false
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 9 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4rnkfrY9byxFp4UnbRDOBw==/app.rvx.manager.flutter-HJOhGOm2qqsfj-NTsgYzqw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-NBDNUO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-NBDNUO/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:487)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hsuHvwTCdC5Nf5dk5fKUQSHxuuY(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4rnkfrY9byxFp4UnbRDOBw==/app.rvx.manager.flutter-HJOhGOm2qqsfj-NTsgYzqw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-NBDNUO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-NBDNUO/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
```

### Solution

If i unninstall an reinstall manager sometimes i can patch

### Additional context

Its same at manager 1.20.4

### Device Environment

Android 14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AbakNacchan** [comment]
Did you try to change RVX Settings name?

**Comment by Ahmey1400** [comment]
Yes.

**Comment by AbakNacchan** [comment]
@anddea the problem is on `RVXSettingsMenuName` as I guessed before.

**Comment by vippium** [comment]
> @anddea the problem is on `RVXSettingsMenuName` as I guessed before.

Created new issue. Wait for anddea to see.

**Comment by Ahmey1400** [comment]
Feel free for the change title

**Comment by anddea** [comment]
I'm aware of this issue and will test it later

**Comment by vippium** [comment]
More simple is just to copy option.json to internal st. Remove that from RVX folder and copy paste
