### ISSUE TITLE
bug: failing patch again with new patch

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#648]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Yt 19.23.40

### Bug description

When i try to rename settings, it fails

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.4
Model: SM-A336E
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.23.40 (Suggested: 19.23.40)
Patches version: v2.226.0-dev.18
Patches added: Custom branding icon YouTube [App icon: mmt_blue], Custom branding name YouTube [App name: RVX Youtube], Force custom branding wordmark header, Force hide player buttons background, Hide Shorts dimming, Hide animated button background, MaterialYou
Patches removed: None
Default patch options changed: Toolbar components [Force hide voice search button: true], Overlay buttons [Icon type: thin], Settings for YouTube [RVX settings menu name: RVX Settings], Visual preferences icons [Extended icon: gear]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Remove unused library: false
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~zBOFGBWDMOu_ohGDmzgvjw==/app.rvx.manager.flutter-dWHGxqZehMcxOsrS9JsFDQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-EWTBOJ/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-EWTBOJ/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:484)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~zBOFGBWDMOu_ohGDmzgvjw==/app.rvx.manager.flutter-dWHGxqZehMcxOsrS9JsFDQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-EWTBOJ/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-EWTBOJ/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
```

### Solution

Keeping the name default

### Device Environment

Android 14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Ahmey1400** [comment]
I fixed it, i cleared the temporary files and reset the patch section its fixed

**Comment by Dhyfer1** [comment]
> I fixed it, i cleared the temporary files and reset the patch section its fixed

How did you do it?

**Comment by Ahmey1400** [comment]
First you need to update patch then go to settings, clear temporary files and logs lastly reset patch selection and patch options.

**Comment by Dhyfer1** [comment]
> First you need to update patch then go to settings, clear temporary files and logs lastly reset patch selection and patch options.

I see, I didn't read well before, my mistake. You are using rvx to patch youtube, I have a problem similar to yours but in my case I use revancify. Using the latest anddes dev patches in rvx I have no problems, my problem is using revancify.

**Comment by anddea** [comment]
> Revancify 

https://github.com/anddea/revanced-patches/issues/641#issuecomment-2185038942

**Comment by Dhyfer1** [comment]
> > Revancify 
> 
> https://github.com/anddea/revanced-patches/issues/641#issuecomment-2185038942

Thank you, I'll have it in mind
