### ISSUE TITLE
bug(YouTube): Custom branding not working

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#714]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube 19.25.39
YouTube Music 7.08.52

### Bug description

As usual, got another resources error while patching. Even though I don't even use the icon.

Then another problem is, when you try to use Custom Branding Name patch on YouTube Music while Custom Branding Icon is included too, the Custom Branding Icon will be excluded.

### Error logs

```shell
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/apk/res/xml/revanced_prefs.xml:719: error: resource string/revanced_icon_revancify_blue (aka rvx.android.youtube:string/revanced_icon_revancify_blue) not found. 
WARNING: error: failed linking file resources. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_168211610595092384667805274165457158581.tmp, link, -o, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1546911168, --version-name, 19.25.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /tmp/APKTOOL8137343323986177663.tmp, -0, arsc, -I, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/1.apk, --manifest, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/apk/AndroidManifest.xml, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:249)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
	at app.revanced.patcher.Patcher.get(Patcher.kt:268)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:324)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_168211610595092384667805274165457158581.tmp, link, -o, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1546911168, --version-name, 19.25.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /tmp/APKTOOL8137343323986177663.tmp, -0, arsc, -I, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/1.apk, --manifest, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/apk/AndroidManifest.xml, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.25.39-arm64-v8a-apk-temporary-files/patcher/apk/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:245)
	... 13 more
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
as usual it's a dev release, not a stable on. will work on this tomorrow
