### ISSUE TITLE
bug: Patch failed

### ISSUE THREAD

**Issue by gigachaand** [anddea/revanced-patches#732]
### Type

Error while patching

### Tools used

Revancify

### Application

19.16.39

### Bug description

None

### Error logs

```shell
INFO: Loading patches 
INFO: Deleting existing temporary files directory 
INFO: Decoding app manifest 
INFO: Enable OPUS codec excluded 
INFO: Translations excluded 
INFO: Disable QUIC protocol excluded 
INFO: Enable debug logging excluded 
INFO: Change player flyout menu toggles excluded 
INFO: Spoof app version excluded 
INFO: Miniplayer excluded 
INFO: Enable gradient loading screen excluded 
INFO: Layout switch excluded 
INFO: Alternative thumbnails excluded 
INFO: Spoof client excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Ambient mode control succeeded 
INFO: Change start page succeeded 
INFO: Custom Shorts action buttons succeeded 
INFO: Custom branding icon for YouTube succeeded 
INFO: Custom branding name for YouTube succeeded 
INFO: Custom double tap length succeeded 
INFO: Custom package name succeeded 
INFO: Description components succeeded 
INFO: Disable auto audio tracks succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable haptic feedback succeeded 
INFO: Disable resuming Shorts on startup succeeded 
INFO: Disable splash animation succeeded 
INFO: Enable external browser succeeded 
INFO: Enable open links directly succeeded 
INFO: Force hide player buttons background succeeded 
INFO: Force snackbar theme succeeded 
INFO: Fullscreen components succeeded 
INFO: GmsCore support succeeded 
INFO: Hide Shorts dimming succeeded 
INFO: Hide action buttons succeeded 
INFO: Hide ads succeeded 
INFO: Hide comments components succeeded 
INFO: Hide feed components succeeded 
INFO: Hide feed flyout menu succeeded 
INFO: Hide layout components succeeded 
INFO: Hide player buttons succeeded 
INFO: Hide player flyout menu succeeded 
INFO: MaterialYou succeeded 
INFO: Navigation bar components succeeded 
INFO: Overlay buttons succeeded 
INFO: Player components succeeded 
INFO: Remove background playback restrictions succeeded 
INFO: Remove viewer discretion dialog succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Sanitize sharing links succeeded 
INFO: Seekbar components succeeded 
INFO: Shorts components succeeded 
INFO: SponsorBlock succeeded 
INFO: Swipe controls succeeded 
INFO: Theme succeeded 
INFO: Toolbar components succeeded 
INFO: Video playback succeeded 
INFO: Visual preferences icons succeeded 
INFO: Settings for YouTube succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiling modified resources 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:279: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:282: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:283: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:284: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:285: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:286: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:287: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:288: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml:289: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values-v31/colors.xml: error: file failed to compile. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:850: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1265: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1267: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1268: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1269: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1270: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1271: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1272: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1331: error: invalid color. 
WARNING: /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res/values/colors.xml:1335: error: invalid color. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, compile, --dir, /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res, --legacy, -o, /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
	at app.revanced.patcher.Patcher.get(Patcher.kt:268)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:324)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, compile, --dir, /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/res, --legacy, -o, /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.16.39/base-RVX-anddea-temporary-files/patcher/apk/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
	... 13 more



Rooted: false
Arch: arm64-v8a
App: YouTube v19.16.39
CLI: inotia00-cli-v4.6.1.jar
Patches: anddea-patches-v2.227.0-dev.22.jar
Integrations: anddea-integrations-v0.154.0-dev.7.apk
Patches argument: -i Ambient mode control -i Change start page -i Custom Shorts action buttons -i Custom branding icon for YouTube -i Custom branding name for YouTube -i Custom double tap length -i Custom package name -i Description components -i Disable auto audio tracks -i Disable auto captions -i Disable haptic feedback -i Disable resuming Shorts on startup -i Disable splash animation -i Enable external browser -i Enable open links directly -i Force hide player buttons background -i Force snackbar theme -i Fullscreen components -i GmsCore support -i Hide Shorts dimming -i Hide action buttons -i Hide ads -i Hide comments components -i Hide feed components -i Hide feed flyout menu -i Hide layout components -i Hide player buttons -i Hide player flyout menu -i MaterialYou -i Navigation bar components -i Overlay buttons -i Player components -i Remove background playback restrictions -i Remove viewer discretion dialog -i Return YouTube Dislike -i Sanitize sharing links -i Seekbar components -i Settings for YouTube -i Shorts components -i SponsorBlock -i Swipe controls -i Theme -i Toolbar components -i Video playback -i Visual preferences icons
```

### Solution

None

### Additional context

None

### Device Environment

None

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Cannot reproduce, try to clear your patching tool - Revancify / Termux.
