### ISSUE TITLE
bug(YouTube - Custom branding icons): Patch fails when the `Stock` icon in selected

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#751]
### Type

Error while patching

### Tools used

rvx-builder

### Application

Latest Recommended

### Bug description

Not able to patch YT as it is showing error on compiling.

### Error logs

```shell
[builder] WARNING: /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/apk/res/values-v31/styles.xml:460: error: resource drawable/avd_anim (aka anddea.youtube:drawable/avd_anim) not found.
[builder] WARNING: /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/apk/res/values-v31/styles.xml:460: error: resource drawable/avd_anim (aka anddea.youtube:drawable/avd_anim) not found.
[builder] WARNING: error: failed linking references.
[builder] brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/data/com.termux/files/usr/tmp/APKTOOL17818146370264870599.tmp, -0, arsc, -I, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/apk/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/apk/build/resources.zip] at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:249) at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394) at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134) at app.revanced.patcher.Patcher.get(Patcher.kt:268) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:324) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12) Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/data/com.termux/files/usr/tmp/APKTOOL17818146370264870599.tmp, -0, arsc, -I, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/apk/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/revanced/revanced-temporary-files/patcher/apk/build/resources.zip] at brut.util.OS.exec(OS.java:104) at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:245) ... 13 more
```

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you specify more details, patches, icons, etc.?

**Comment by vippium** [comment]
> Can you specify more details, patches, icons, etc.?

This only happening when selecting Custom Icon patch. Rather than, it is working fine

> Did you clear your patching tool?
Rvx-builder. But it is happening on every method.

**Comment by anddea** [comment]
> Custom Icon

I think so too, what icon did you use? I'll try to fix it in 24 hours.

**Comment by vippium** [comment]
> > Custom Icon
> 
> I think so too, what icon did you use? I'll try to fix it in 24 hours.

Kuch stock one. Also tried with default revancify yellow

**Comment by anddea** [comment]
Yes, stock icon is not working but you can use it if you exclude custom icon at all. Revancify icons work fine.

**Comment by zerozero0022** [comment]
Checking and patching 'Custom Branding Icon for YouTube' causes an error. 

YouTube, Vanced Light, and Vanced Black do not have Old style splash Animation, so 'Restore Old Splash Animation' should be unchecked.
