### ISSUE TITLE
bug: encountered an error while patching 

### ISSUE THREAD

**Issue by rsaurav12** [anddea/revanced-patches#754]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Trying to patch YouTube 19.25.39

### Bug description

- Device Info
ReVanced Manager: 1.20.4
Model: Redmi Note 9 Pro
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.25.39 (Suggested: 19.16.39)
Patches version: v2.227.1-dev.1
Patches added: Custom branding icon for YouTube [App icon: mmt], Custom branding name for YouTube [App name: YouTube], Hide Shorts dimming
Patches removed: Disable splash animation, Enable debug logging, Translations
Default patch options changed: Custom Shorts action buttons [Shorts icon style : outline], Visual preferences icons [Extended icon: gear], Overlay buttons [Icon type: thin]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: true
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Alternative thumbnails failed: app.revanced.patcher.patch.PatchException: 'Alternative thumbnails' depends on 'CronetImageUrlHookPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Collection contains more than one matching element.
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:239)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:459)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalArgumentException: Collection contains more than one matching element.
	at app.revanced.patches.shared.imageurlhook.BaseCronetImageUrlHookPatch.execute(BaseCronetImageUrlHookPatch.kt:142)
	at app.revanced.patches.shared.imageurlhook.BaseCronetImageUrlHookPatch.execute(BaseCronetImageUrlHookPatch.kt:26)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	... 19 more

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:148)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:459)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Applied 50 patches
Bypass image region restrictions failed: app.revanced.patcher.patch.PatchException: 'Bypass image region restrictions' depends on 'CronetImageUrlHookPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'CronetImageUrlHookPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:45)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:459)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:148)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:459)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 4 dex files

### Device Environment

Android 12
Miui 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
19.25.39 is not supported, the latest supported is 19.16.39.
