### ISSUE TITLE
Bug: using manager on android, patching alwa6s fails

### ISSUE THREAD

**Issue by Wojtaz0w** [anddea/revanced-patches#76]
- Device Info
ReVanced Manager: 1.19.3
Model: Redmi 9
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.09.37 (Suggested: 19.05.36)
Patches version: v2.221.1
Patches added: Custom branding heading, Custom branding icon YouTube [App icon: revancify_red], Custom branding name YouTube [App name: YouTube ReVanced], Hide animated button background, Hide player buttons background, MaterialYou
Patches removed: None
Default patch options changed: Custom package name [Package name of YouTube: app.rvx.android.youtube], Shorts overlay buttons [Icon type of Shorts: outline]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 113 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
t0.b: d1.a: could not exec (exit code = 1): [/data/app/~~EW6wjyYHJ_gerRCKW92jzA==/app.revanced.manager.flutter-Sm7PmJ4wmcMnZPzVY52fWw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HLNIIH/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HLNIIH/revanced-temporary-files/apk/build/resources.zip]
	at r0.a.f(Unknown Source:144)
	at r0.a.d(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:1)
	at app.revanced.patcher.Patcher.get(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: d1.a: could not exec (exit code = 1): [/data/app/~~EW6wjyYHJ_gerRCKW92jzA==/app.revanced.manager.flutter-Sm7PmJ4wmcMnZPzVY52fWw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HLNIIH/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HLNIIH/revanced-temporary-files/apk/build/resources.zip]
	at f1.h.b(Unknown Source:75)
	at r0.a.f(Unknown Source:122)
	... 7 more

Step: compiling resources always fails, both on RV and RVX Manager.

**Comment by anddea** [comment]
Use RVX Manager, as Rv is incompatible. Clear storage or reinstall RVX Manager, as it might keep some old artifacts that cause errors. It'll delete cache so change sources after that again.

**Comment by Wojtaz0w** [comment]
It works on rvx manager, thanks
