### ISSUE TITLE
bug(YouTube Music - Visual preferences icons): Patch fails when `Extended icon` is `Stock` icon

### ISSUE THREAD

**Issue by stainlf** [anddea/revanced-patches#773]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube Music v7.12.51

### Bug description

When Custom branding icon is selected and is YouTube Music and `Extended icon` is Custom branding icon, Patch fails 

inotia00's patch hasn't even merged the Visual preferences icons in yet, so maybe the bug below still persists in anddea patch's YouTube Music.
https://github.com/inotia00/ReVanced_Extended/issues/2181

### Error logs

```shell
- Device Info
RVX Manager: 1.21.1
Model: SM-S928N
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v7.12.51 (Suggested: 7.12.51)
Patches version: v2.228.0-dev.3
Patches added: Custom branding icon for YouTube Music [App icon: youtube_music, Change header: false, Change splash icons: false], Custom branding name for YouTube Music [App name in notification panel: YT Music, App name in launcher: YT Music]
Patches removed: Enable Cairo splash animation, Amoled, Restore old style library shelf, Enable debug logging, Bypass image region restrictions, Translations
Default patch options changed: Settings for YouTube Music [RVX settings menu name: RVX Settings], Visual preferences icons [Extended icon: custom_branding_icon]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: true
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 26 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~lrh4me7YzdLOply_GOvGfw==/app.rvx.manager.flutter-RrE8UGZoEsp_3ormH5RuwA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 71251240, --version-name, 7.12.51, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL3401689597175864797.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:486)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~lrh4me7YzdLOply_GOvGfw==/app.rvx.manager.flutter-RrE8UGZoEsp_3ormH5RuwA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 71251240, --version-name, 7.12.51, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL3401689597175864797.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.rvx.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YAZQBU/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Solution

I would appreciate it if you could implement the `Stock` icon for `Extended icon` just like YouTube on YouTube Music to fix the above bug. 

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
i can't reproduce this on my end, make sure you clear your patch options since `Stock` one has been removed some weeks ago

**Comment by anddea** [comment]
I'll check and update the icon for Music too. I just don't know when I'll be able to do that.

**Comment by Francesco146** [comment]
there's no `Stock` icon, there was some time ago, now it's called `YouTube Music`.

**Comment by anddea** [comment]
Not a problem I guess. If you have icons, you can share them with the original link of their author, so we can speed it up. Even better if it's SVG, from website like https://www.svgrepo.com/

**Comment by anddea** [comment]
This white background will be invisible in light theme, so maybe it's better without it. Share original links also, so we can add authors in a commit.

**Comment by anddea** [comment]
Yes, I remember that I mentioned this before but still that white background is not visible. 

I mean direct links where you got those icons from. Or I'll have to make those icons myself and it will take longer time.

**Comment by anddea** [comment]
Updated icons in the latest release.

**Comment by anddea** [comment]
The rounded icon does not look good even with a white background. Previously, the squircle icon looked okay, but we made them all circle-shaped for consistency.
