### ISSUE TITLE
bug: Unescaped Apostrophe in String

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#795]
### Type

Error while patching

### Tools used

CLI

### Application

Supported YT version

### Bug description

unescaped apostrophe in string

### Error logs

```shell
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:319: error: unescaped apostrophe in string 
WARNING: "Visualizza la finestra di ottimizzazione per GMSCore a ogni avvio dell'applicazione.". 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:319: error: not a valid string. 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:756: error: unescaped apostrophe in string 
WARNING: "Il pulsante dei commenti disabilitato o con l'etichetta \"0\" sono mostrati.". 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:756: error: not a valid string. 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:757: error: unescaped apostrophe in string 
WARNING: "Il pulsante dei commenti disabilitato o con l'etichetta \"0\" sono nascosti.". 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:757: error: not a valid string. 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:1215: error: unescaped apostrophe in string 
WARNING: "Regolazione: Segna l'ora di inizio e di fine del segmento". 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml:1215: error: not a valid string. 
WARNING: /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res/values-it-rIT-v21/strings.xml: error: file failed to compile. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_16370545526223221544002930339499562418.tmp, compile, --dir, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res, --legacy, -o, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
	at app.revanced.patcher.Patcher.get(Patcher.kt:268)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:324)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_16370545526223221544002930339499562418.tmp, compile, --dir, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/res, --legacy, -o, /home/runner/work/RV-X/RV-X/temp/youtube-rv-x-19.16.39-arm64-v8a-apk-temporary-files/patcher/apk/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
	... 13 more
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
fixed in https://github.com/anddea/revanced-patches/commit/936c74067d896cc779fc15eec61116eb20862f09
