### ISSUE TITLE
bug: `Change player flyout panel toggles` fails on supported version

### ISSUE THREAD

**Issue by Kuddus73** [anddea/revanced-patches#82]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.05.36
Patches v2.221.1

### Bug description

The patching of `Change player flyout panel toggles` patch fails on YouTube v19.05.36, which is the supported version.
The error log says that the YouTube version is not supported and to use v19.05.36, although I'm already using v19.05.36 while patching.
Note that the patch doesn't fail with ReX source.

### Error logs

- Patch Info
App: [com.google.android.youtube](http://com.google.android.youtube/) v[19.05.36](tel:190536) (Suggested: [19.05.36](tel:190536))
Patches version: v[2.221.1](tel:22211)

- Settings
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 108 patches
Change player flyout panel toggles failed: app.revanced.patcher.patch.PatchException: This version is not supported. Please use YouTube [19.05.36](tel:190536) or earlier.
	at [app.revanced.patches.youtube](http://app.revanced.patches.youtube/).flyoutpanel.player.ChangeTogglePatch.execute(ChangeTogglePatch.kt:74)
	at [app.revanced.patches.youtube](http://app.revanced.patches.youtube/).flyoutpanel.player.ChangeTogglePatch.execute(ChangeTogglePatch.kt:23)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:1)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:2)
	at b6.f.b(Unknown Source:2)
	at b6.a.a(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at [y5.o0.run](http://y5.o0.run/)(Unknown Source:93)
	at y5.u0.P(Unknown Source:46)
	at y5.e.t0(Unknown Source:23)
	at y5.h.a(Unknown Source:73)
	at y5.g.c(Unknown Source:0)
	at y5.h.b(Unknown Source:6)
	at y5.g.d(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at [app.revanced.manager.flutter.f.run](http://app.revanced.manager.flutter.f.run/)(Unknown Source:20)
	at [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:1012](http://thread.java:1012/))

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
i can reproduce the issue, this is still happening to the latest versions.

**Comment by anddea** [comment]
Yep, was preserved from last `ReX` merge to this repo. Fixed in the latest dev release. You can update it.

**Comment by Kuddus73** [comment]
> Yep, was preserved from last `ReX` merge to this repo. Fixed in the latest dev release. You can update it.

Can't update until it is a pre-release.

**Comment by anddea** [comment]
> Can't update until it is a pre-release.

RVX Manager shows pre-releases too. It's not a good idea that it does this, but I don't wanna fork it and change this behavior just to maintain yet another thing in my life.
