### ISSUE TITLE
bug: Can't patch youtube

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#844]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube 19.16.39
Latest [patches](https://github.com/anddea/revanced-patches/releases/tag/v2.230.0-dev.1)

### Bug description

When i try to patch youtube using cli i get error message on last steps

### Error logs

```shell
C:\Users\Ayxan\Desktop\cli>java -jar revanced-cli.jar patch YT16.apk -o Afnify.apk --options options.json -b revanced-patches.jar -m revanced-integrations.apk --rip-lib=x86 --rip-lib=x86_64 --rip-lib=armeabi-v7a --include="Custom branding icon for YouTube" --include="Custom branding name for YouTube" --include="MaterialYou" -f
INFO: Loading patches
INFO: Deleting existing temporary files directory
INFO: Decoding app manifest
INFO: Change version code excluded
INFO: Hide Shorts dimming excluded
INFO: Hide shortcuts excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing temporary files directory
INFO: Decoding resources
INFO: Executing patches
INFO: Alternative thumbnails succeeded
INFO: Ambient mode control succeeded
INFO: Bypass image region restrictions succeeded
INFO: Change player flyout menu toggles succeeded
INFO: Change share sheet succeeded
INFO: Change start page succeeded
INFO: Custom Shorts action buttons succeeded
INFO: Custom branding icon for YouTube succeeded
INFO: Custom branding name for YouTube succeeded
INFO: Custom double tap length succeeded
INFO: Description components succeeded
INFO: Disable QUIC protocol succeeded
INFO: Disable auto audio tracks succeeded
INFO: Disable auto captions succeeded
INFO: Disable haptic feedback succeeded
INFO: Disable resuming Shorts on startup succeeded
INFO: Disable splash animation succeeded
INFO: Enable OPUS codec succeeded
INFO: Enable debug logging succeeded
INFO: Enable external browser succeeded
INFO: Enable gradient loading screen succeeded
INFO: Enable open links directly succeeded
INFO: Force player buttons background succeeded
INFO: Force snackbar theme succeeded
INFO: Fullscreen components succeeded
INFO: GmsCore support succeeded
INFO: Hide action buttons succeeded
INFO: Hide ads succeeded
INFO: Hide comments components succeeded
INFO: Hide feed components succeeded
INFO: Hide feed flyout menu succeeded
INFO: Hide layout components succeeded
INFO: Hide player buttons succeeded
INFO: Hide player flyout menu succeeded
INFO: Hook download actions succeeded
INFO: Layout switch succeeded
INFO: MaterialYou succeeded
INFO: Miniplayer succeeded
INFO: Navigation bar components succeeded
INFO: Overlay buttons succeeded
INFO: Player components succeeded
INFO: Remove background playback restrictions succeeded
INFO: Remove viewer discretion dialog succeeded
INFO: Return YouTube Dislike succeeded
INFO: Sanitize sharing links succeeded
INFO: Seekbar components succeeded
INFO: Shorts components succeeded
INFO: SponsorBlock succeeded
INFO: Spoof app version succeeded
INFO: Spoof streaming data succeeded
INFO: Spoof watch history succeeded
INFO: Swipe controls succeeded
INFO: Theme succeeded
INFO: Toolbar components succeeded
INFO: Translations succeeded
INFO: Video playback succeeded
INFO: Visual preferences icons succeeded
INFO: Hook YouTube Music actions succeeded
INFO: Settings for YouTube succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
WARNING: C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\apk\res\drawable\avd_anim.xml: error: resource 'drawable/$avd_anim__0' has a conflicting value for configuration ().
WARNING: C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\apk\res\drawable\$avd_anim__0.xml: note: originally defined here.
WARNING: error: failed parsing input.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ayxan\AppData\Local\Temp\brut_util_Jar_74938184773623668797587250152545788770.tmp, link, -o, C:\Users\Ayxan\Desktop\Andoid development\cli (anddea)\Afnify-temporary-files\patcher\patched\resources\resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, C:\Users\Ayxan\AppData\Local\Temp\APKTOOL15382522182963610495.tmp, -0, arsc, -I, C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\1.apk, --manifest, C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\apk\AndroidManifest.xml, C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\apk\build\resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:249)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
        at app.revanced.patcher.Patcher.get(Patcher.kt:268)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:324)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ayxan\AppData\Local\Temp\brut_util_Jar_74938184773623668797587250152545788770.tmp, link, -o, C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\patched\resources\resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, C:\Users\Ayxan\AppData\Local\Temp\APKTOOL15382522182963610495.tmp, -0, arsc, -I, C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\1.apk, --manifest, C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\apk\AndroidManifest.xml, C:\Users\Ayxan\Desktop\cli\Afnify-temporary-files\patcher\apk\build\resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:245)
        ... 13 more
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by infamousdimsum** [comment]
Disable pre release patch settings. Something going on with the latest dev build that's causing those errors.

**Comment by anddea** [comment]
It should be only with AFN icons, do you have this issue with other icons?

**Comment by AykhanUV** [comment]
Yeah i have used "afn_blue" icon and now it works
